"""adding balance

Revision ID: 7af14a82fdd3
Revises: e02b25a1f7f3
Create Date: 2024-05-21 00:20:10.600276

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7af14a82fdd3"
down_revision: Union[str, None] = "e02b25a1f7f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bankaccount", schema=None) as batch_op:
        batch_op.add_column(sa.Column("balance", sa.Numeric(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bankaccount", schema=None) as batch_op:
        batch_op.drop_column("balance")

    # ### end Alembic commands ###
