"""adding state and annotations to AccountTransaction

Revision ID: aa21f05dcac1
Revises: 7af14a82fdd3
Create Date: 2024-05-26 21:00:29.186256

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa21f05dcac1"
down_revision: Union[str, None] = "7af14a82fdd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounttransaction", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "state", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.add_column(sa.Column("annotations", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounttransaction", schema=None) as batch_op:
        batch_op.drop_column("annotations")
        batch_op.drop_column("state")

    # ### end Alembic commands ###
