"""initial

Revision ID: e02b25a1f7f3
Revises: 
Create Date: 2024-05-20 17:17:47.371591

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e02b25a1f7f3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bankaccount",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bankaccount")),
        sa.UniqueConstraint(
            "account_number", name=op.f("uq_bankaccount_account_number")
        ),
    )
    with op.batch_alter_table("bankaccount", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bankaccount_id"), ["id"], unique=False
        )

    op.create_table(
        "accounttransaction",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("account_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=9, scale=2), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["bankaccount.id"],
            name=op.f("fk_accounttransaction_account_id_bankaccount"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounttransaction")),
    )
    with op.batch_alter_table("accounttransaction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accounttransaction_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounttransaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounttransaction_id"))

    op.drop_table("accounttransaction")
    with op.batch_alter_table("bankaccount", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bankaccount_id"))

    op.drop_table("bankaccount")
    # ### end Alembic commands ###
