"""initial

Revision ID: 4b79f1f6a758
Revises: 
Create Date: 2024-05-20 17:01:39.704491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "4b79f1f6a758"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("swift", sa.String(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bank_metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank")),
        sa.UniqueConstraint("swift", name=op.f("uq_bank_swift")),
    )
    with op.batch_alter_table("bank", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bank_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bank", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bank_id"))

    op.drop_table("bank")
    # ### end Alembic commands ###
